#Marta Konarska

print("This program calculates and displays travel expenses")
print("")
budget = int(input("Enter Budget: "))
print("")
location = input("Enter your travel destination: ")
print("")
gas = int(input("How much do you think you will spend on gas? "))
print("")
hotel = int(input("Approximately, how much will you need for accomondation/hotel? "))
print("")
food = int(input("Last, how much do you need for food? "))
print("")
print("----------Travel Expenses---------")
print("Location: " + str(location) + '.')
#print(Location: ",location)
print("Initial Budget: ",budget)
print("")
print("Fuel: ",gas)
print("")
print("Accomodation: ",hotel)
print("")
print("Food: ",food)
print("")
balance = budget - gas - hotel - food
print("Remaining Balance: ",balance)
print("Remaining Balance:", budget - gas - hotel - food)
